### ISSUE TITLE
`dynamic_assert` is basically done by `assert` from `cassert`

### ISSUE THREAD

**Issue by Nicholas-Baron** [JamesGaier/SDL-Mario#1]
https://github.com/JamesGaier/SDL-Mario/blob/71917731748b2f51d1cdd1c3b2548512b0127349/include/Util.hpp#L7-L18

If the `msg` parameter is not needed, the standard provides something similar: https://en.cppreference.com/w/cpp/error/assert

**Comment by JamesGaier** [comment]
done
